### ISSUE TITLE
Adding Spectacle to Hackage & nixpkgs?

### ISSUE THREAD

**Issue by byrongibson** [awakesecurity/spectacle#31]
Hi all, cool project, any plans to add it to Hackage and Nixpkgs?  I see you're already Nix users.  

I submitted a [packaging request](https://github.com/NixOS/nixpkgs/issues/135145#issuecomment-904955871) for it, and they asked me to check if it's being included Hackage, which would make it easier to add to nixpkgs.

**Comment by ixmatus** [comment]
Spectacle has been released at version 1.0.0 and published to Hackage: https://hackage.haskell.org/package/spectacle. Nixpkgs should pick this up automatically now.
