### ISSUE TITLE
How to disable a formula?

### ISSUE THREAD

**Issue by yagehu** [awakesecurity/spectacle#36]
In TLA+, I can disable a formula by giving a conjunction like so:

```
Action ==
    /\  state = 0
    /\  state' = 1
```

Here, `Action` is only enabled when `state` is 0. How can I express this in Spectacle? Do I `return False` from an action? A minimal example would be nice.

**Comment by ixmatus** [comment]
@yagehu that is correct. `return False` disables an action. We plan to write a lot more documentation soon.
